### ISSUE TITLE
Fails to build on Python 3.13

### ISSUE THREAD

**Issue by stefanor** [GrahamDumpleton/mod_wsgi#907]
```
src/server/wsgi_interp.c:2223:17: error: implicit declaration of function 'PySys_AddWarnOption'; did you mean 'PySys_ResetWarnOptions'? [-Wimplicit-function-declaration]
 2223 |                 PySys_AddWarnOption(s);
      |                 ^~~~~~~~~~~~~~~~~~~
      |                 PySys_ResetWarnOptions
src/server/wsgi_interp.c:2384:17: warning: 'Py_SetProgramName' is deprecated [-Wdeprecated-declarations]
 2384 |                 Py_SetProgramName(s);
      |                 ^~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.13/Python.h:119:
```

https://docs.python.org/3.13/whatsnew/3.13.html#removed-c-apis

**Comment by GrahamDumpleton** [comment]
Known about via pr https://github.com/GrahamDumpleton/mod_wsgi/pull/883

Changes had been merged to `develop` branch just before you created this issue.

You can for now use:

```
pip install https://github.com/GrahamDumpleton/mod_wsgi/archive/refs/heads/develop.zip
```

A `mod_wsgi-5.0.1.dev1` release will be made soon to facilitate further testing.

**Comment by GrahamDumpleton** [comment]
Version 5.0.1.rc1 is released on PyPi now if want to give that a try on Python 3.13.

**Comment by GrahamDumpleton** [comment]
Version 5.0.1 has been release. Please let me know if still having issues with it.
