### ISSUE TITLE
mod_wsgi fails to build with Python 3.11.0a4

### ISSUE THREAD

**Issue by abbra** [GrahamDumpleton/mod_wsgi#760]
Copying Fedora issue https://bugzilla.redhat.com/show_bug.cgi?id=2049695 here upstream for awareness. Looks like a relatively simple to fix for Python 3.8+?:

```
src/server/mod_wsgi.c: In function 'wsgi_log_stack_traces':
src/server/mod_wsgi.c:9528:58: error: 'PyFrameObject' {aka 'struct _frame'} has no member named 'f_code'
 9528 |                         lineno = PyCode_Addr2Line(current->f_code,
      |                                                          ^~
src/server/mod_wsgi.c:9529:58: error: 'PyFrameObject' {aka 'struct _frame'} has no member named 'f_lasti'
 9529 |                                                   current->f_lasti);
      |                                                          ^~
src/server/mod_wsgi.c:9533:56: error: 'PyFrameObject' {aka 'struct _frame'} has no member named 'f_code'
 9533 |                     filename = PyUnicode_AsUTF8(current->f_code->co_filename);
      |                                                        ^~
src/server/mod_wsgi.c:9534:52: error: 'PyFrameObject' {aka 'struct _frame'} has no member named 'f_code'
 9534 |                     name = PyUnicode_AsUTF8(current->f_code->co_name);
      |                                                    ^~
apxs:Error: Command failed with rc=65536

Changes of the PyFrameObject structure members:
    f_code: removed, use PyFrame_GetCode() instead. Warning: the function returns a strong reference, need to call Py_DECREF().
    f_back: changed, use PyFrame_GetBack().
    f_builtins: removed, use PyObject_GetAttrString(frame, "f_builtins").
    f_globals: removed, use PyObject_GetAttrString(frame, "f_globals").
    f_locals: removed, use PyObject_GetAttrString(frame, "f_locals").
    f_lasti: removed, use PyObject_GetAttrString(frame, "f_lasti").
    f_valuesstack: removed.
    f_stackdepth: removed.
    f_gen: removed.
    f_iblock: removed.
    f_state: removed.
    f_blockstack: removed.
    f_localsplus: removed.
```
The Python frame object is now created lazily. A side effect is that the f_back member must not be accessed directly, since its value is now also computed lazily. The `PyFrame_GetBack()` function must be called instead.

Code defining `PyFrame_GetCode()` on Python 3.8 and older:

https://docs.python.org/3.11/whatsnew/3.11.html

For the build logs, see:
https://copr-be.cloud.fedoraproject.org/results/@python/python3.11/fedora-rawhide-x86_64/03271443-mod_wsgi/

For all our attempts to build mod_wsgi with Python 3.11, see:
https://copr.fedorainfracloud.org/coprs/g/python/python3.11/package/mod_wsgi/

Testing and mass rebuild of packages is happening in copr. You can follow these instructions to test locally in mock if your package builds with Python 3.11:
https://copr.fedorainfracloud.org/coprs/g/python/python3.11/

Let us know here if you have any questions.

Python 3.11 is planned to be included in Fedora 37. To make that update smoother, we're building Fedora packages with all pre-releases of Python 3.11.
A build failure prevents us from testing all dependent packages (transitive [Build]Requires), so if this package is required a lot, it's important for us to get it fixed soon.
We'd appreciate help from the people who know this package best, but if you don't want to work on this now, let us know so we can try to work around it on our side.

**Comment by GrahamDumpleton** [comment]
Closing this at this point as latest release (4.9.1) should at least compile. Whether it falls over and bursts into flames at runtime because of other Python 3.11 changes will be a different matter. :-)
